# Generated by Django 3.0.6 on 2020-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('brand', models.TextField()),
                ('name', models.TextField()),
                ('condition', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('storage_location', models.TextField()),
                ('hire_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('notes', models.TextField()),
            ],
        ),
    ]
