# Generated by Django 3.0.6 on 2020-06-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.HireRequest')),
            ],
        ),
    ]
