# Generated by Django 3.0.6 on 2020-06-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hire', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.HireRequest')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedCustomItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.HireRequest')),
            ],
        ),
    ]
