# Generated by Django 3.0.6 on 2020-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('cid', models.CharField(blank=True, max_length=16, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('colour', models.CharField(default='#000000', max_length=7)),
                ('event_from', models.DateField()),
                ('event_to', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('cid', models.CharField(blank=True, max_length=16, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('colour', models.CharField(default='#000000', max_length=7)),
                ('hire_from', models.DateField()),
                ('hire_to', models.DateField()),
                ('description', models.TextField()),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('for_csp', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
