# Generated by Django 3.0.6 on 2020-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_hirerequest_for_csp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
