# Generated by Django 3.0.6 on 2020-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20200611_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
