# Generated by Django 3.0.6 on 2020-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_auto_20200611_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
