name: master branch
on:
  push:
    branches:
      - master

jobs:
  docker_build:
    name: Build a Docker image
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile -t keeptrack:latest .
  check:
    name: Django system check
    runs-on: [self-hosted]
    needs: docker_build
    steps:
      - env:
          SECRET: dummy
        run: docker run --env SECRET_KEY=$SECRET --env APP_DEBUG=1 keeptrack:latest python3 /var/django/manage.py check
  test:
    name: Tests
    needs: [docker_build, check]
    runs-on: [self-hosted]
    steps:
      - env:
          SECRET: dummy
        run: docker run --env SECRET_KEY=$SECRET --env APP_DEBUG=1 keeptrack:latest python3 /var/django/manage.py test
  deploy:
    name: Deployment to production
    needs: [docker_build, check, test]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:push -a keeptrack-imperial web
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:release -a keeptrack-imperial web
