name: testing branch
on:
  push:
    branches:
      - testing

jobs:
  check:
    name: Django system check
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          APP_DEBUG: 1
        run: python3 manage.py check
  test:
    name: Tests
    needs: check
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          APP_DEBUG: 1
        run: python3 manage.py test
  deploy:
    name: Deployment to testing
    needs: [check, test]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile -t keeptrack:latest-test .
      - run: docker kill keeptrack-testing || true
      - run: docker rm keeptrack-testing || true
      - env:
          SECRET: ${{ secrets.DJANGO_SECRET_KEY }}
        run: docker run --env SECRET_KEY=$SECRET --env APP_DEBUG=1 --env PORT=8080 -p 8080:8080 --name keeptrack-testing -d keeptrack:latest-test
